CREATE DATABASE Restaurante3BD;
go
USE Restaurante3BD;
go  

  CREATE TABLE ESTADO ( 
  Id TINYINT PRIMARY KEY IDENTITY (1,1),
  Nombre VARCHAR (50) NOT NULL 
  );
  GO

  
CREATE TABLE dbo.Rol (
IdRol INT IDENTITY PRIMARY KEY,
NombreRol VARCHAR(50) NOT NULL UNIQUE,
IdEstado  TINYINT FOREIGN KEY REFERENCES ESTADO (Id)
);
 
 
CREATE TABLE dbo.Usuario (
IdUsuario INT IDENTITY PRIMARY KEY,
Nombre VARCHAR(100) NOT NULL,
Correo VARCHAR(150) NOT NULL UNIQUE,
Clave VARCHAR(255) NOT NULL,
IdRol INT NOT NULL REFERENCES dbo.Rol(IdRol),
Estado BIT NOT NULL DEFAULT 1,
IdEstado  TINYINT FOREIGN KEY REFERENCES ESTADO (Id)
);

IF NOT EXISTS (SELECT 1 FROM dbo.Rol
WHERE NombreRol='Administrador')
INSERT dbo.Rol VALUES ('Administrador');
IF NOT EXISTS (SELECT 1 FROM dbo.Rol
WHERE NombreRol='Vendedor')
INSERT dbo.Rol VALUES ('Vendedor');
IdEstado  TINYINT FOREIGN KEY REFERENCES ESTADO (Id)



CREATE TABLE DEPARTAMENTO (
    Id TINYINT PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(50) NOT NULL,
    IdDEPARTAMENTO TINYINT NOT NULL,
    FOREIGN KEY (IdDEPARTAMENTO) REFERENCES DEPARTAMENTO(Id), 
    IdEstado  TINYINT FOREIGN KEY REFERENCES ESTADO (Id)
    );



CREATE TABLE MUNICIPIO (
    Id TINYINT PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(50) NOT NULL,
    IdDEPARTAMENTO TINYINT NOT NULL,
    FOREIGN KEY (IdDEPARTAMENTO) REFERENCES DEPARTAMENTO(Id),
	IdEstado  TINYINT FOREIGN KEY  REFERENCES ESTADO (Id)
);


CREATE TABLE DISTRITO (
    Id TINYINT PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(50) NOT NULL,
    IdMUNICIPIO TINYINT NOT NULL,
    FOREIGN KEY (IdMUNICIPIO) REFERENCES MUNICIPIO(Id),
	IdEstado  TINYINT FOREIGN KEY  REFERENCES ESTADO (Id)
);


CREATE TABLE ESTADOCARGO (
    Id INT PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(30) NOT NULL,
	IdEstado  TINYINT FOREIGN KEY  REFERENCES ESTADO (Id)
);


CREATE TABLE CARGO (
    Id INT PRIMARY KEY IDENTITY (1,1),
    IdESTADOCARGO INT NOT NULL,
    Nombre VARCHAR(50) NOT NULL,
    Descripcion TEXT,
    FOREIGN KEY (IdESTADOCARGO) REFERENCES ESTADOCARGO(Id),
	IdEstado  TINYINT FOREIGN KEY  REFERENCES ESTADO (Id)
);


CREATE TABLE TURNO (
    Id INT PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(30) NOT NULL,
    HoraEntrada TIME NOT NULL,
    HoraSalida TIME NOT NULL,
    IdEstado  TINYINT FOREIGN KEY  REFERENCES ESTADO (Id)
);


CREATE TABLE EMPLEADO (
    Id INT PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    Direccion VARCHAR(100),
    Telefono VARCHAR(15),
    Email VARCHAR(50),
    IdCargo INT NOT NULL,
    IdSalario INT NOT NULL, 
    FechaIngreso DATE NOT NULL,
    EstadoCARGA VARCHAR(20) NOT NULL,
    FOREIGN KEY (IdCARGO) REFERENCES CARGO(Id),
	IdEstado  TINYINT FOREIGN KEY  REFERENCES ESTADO (Id)
);


CREATE TABLE EMPLEADO_TURNO (
    Id INT PRIMARY KEY IDENTITY (1,1),
    IdEmpleado INT NOT NULL,
    IdTurno INT NOT NULL,
    FOREIGN KEY (IdEmpleado) REFERENCES EMPLEADO(Id),
    FOREIGN KEY (IdTurno) REFERENCES TURNO(Id),
	IdEstado  TINYINT FOREIGN KEY  REFERENCES ESTADO (Id)
);


CREATE TABLE TPOCLIENTE (
    Id INT PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(30) NOT NULL,
    Descripcion VARCHAR(100),
    Estado VARCHAR(20) NOT NULL,
   IdEstado  TINYINT FOREIGN KEY  REFERENCES ESTADO (Id)
);


CREATE TABLE CLIENTE (
    Id INT PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    Direccion VARCHAR(100),
    IdDistrito TINYINT NOT NULL,
    Email VARCHAR(50),
    FOREIGN KEY (IdDistrito) REFERENCES DISTRITO(Id),
	IdEstado  TINYINT FOREIGN KEY  REFERENCES ESTADO (Id)
);


CREATE TABLE CLIENTE_TIPO (
    Id INT PRIMARY KEY IDENTITY (1,1),
    IdCliente INT NOT NULL,
    IdTipoCliente INT NOT NULL,
    FechaAsignacion DATE NOT NULL,
    Estado VARCHAR(20) NOT NULL,
    FOREIGN KEY (IdCliente) REFERENCES CLIENTE(Id),
    FOREIGN KEY (IdTipoCliente) REFERENCES TPOCLIENTE(Id),
	IdEstado  TINYINT FOREIGN KEY  REFERENCES ESTADO (Id)
);


CREATE TABLE RESERVA_CLIENTE (
    Id INT PRIMARY KEY IDENTITY (1,1),
    IdCliente INT NOT NULL,
    FechaReserva DATE NOT NULL,
    HoraReserva TIME NOT NULL,
    CantidadPersonas INT NOT NULL,
    Observaciones VARCHAR(150),
    Estado VARCHAR(20) NOT NULL,
    FOREIGN KEY (IdCliente) REFERENCES CLIENTE(Id),
    IdEstado  TINYINT FOREIGN KEY  REFERENCES ESTADO (Id)
);


CREATE TABLE UBICACIONMESA (
    Id INT PRIMARY KEY IDENTITY (1,1),
    Mesas VARCHAR(50) NOT NULL, 
    IdEstado  TINYINT FOREIGN KEY  REFERENCES ESTADO (Id)
);


CREATE TABLE MESAS (
    Id INT PRIMARY KEY IDENTITY (1,1),
    IdNumero INT NOT NULL,
    Capacidad INT NOT NULL,
    IdUbicacion INT NOT NULL,
    Estado VARCHAR(20) NOT NULL,
    FOREIGN KEY (IdUbicacion) REFERENCES UBICACIONMESA(Id),
    IdEstado  TINYINT FOREIGN KEY  REFERENCES ESTADO (Id)
);


CREATE TABLE RESERVACION (
    Id INT PRIMARY KEY IDENTITY (1,1),
    IdCliente INT NOT NULL,
    Fecha VARCHAR(30) NOT NULL, 
    Hora VARCHAR(20) NOT NULL,
    NumeroPersonas INT NOT NULL,
    IdMesas INT NOT NULL,
    Telefono VARCHAR(15),
    FOREIGN KEY (IdCliente) REFERENCES CLIENTE(Id),
    FOREIGN KEY (IdMesas) REFERENCES MESAS(Id),
    IdEstado  TINYINT FOREIGN KEY  REFERENCES ESTADO (Id)
);


CREATE TABLE ESTADOPEDIDO (
    Id INT PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(30) NOT NULL,
    IdEstado  TINYINT FOREIGN KEY  REFERENCES ESTADO (Id)
);


CREATE TABLE PEDIDO (
    Id INT PRIMARY KEY IDENTITY (1,1),
    IdCliente INT NOT NULL,
    IdMesa INT NOT NULL,
    IdEmpleado INT NOT NULL,
    FechaPedido DATE NOT NULL,
    HoraPedido TIME NOT NULL,
    IdEstadoPedido INT NOT NULL,
    TotalPagar DECIMAL(10,2) NOT NULL,
    IdReservacion INT,
    FOREIGN KEY (IdCliente) REFERENCES CLIENTE(Id),
    FOREIGN KEY (IdMesa) REFERENCES MESAS(Id),
    FOREIGN KEY (IdEmpleado) REFERENCES EMPLEADO(Id),
    FOREIGN KEY (IdEstadoPedido) REFERENCES ESTADOPEDIDO(Id),
    IdEstado  TINYINT FOREIGN KEY  REFERENCES ESTADO (Id)
);


CREATE TABLE METODOPAGO (
    Id INT PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(30) NOT NULL,
    IdEstado  TINYINT FOREIGN KEY  REFERENCES ESTADO (Id)
);


CREATE TABLE ESTADOPAGO (
    Id INT PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(30) NOT NULL,
    IdEstado  TINYINT FOREIGN KEY  REFERENCES ESTADO (Id)
);


CREATE TABLE PAGOS (
    IdPago INT PRIMARY KEY IDENTITY (1,1),
    IdPedido INT NOT NULL,
    IdMetodoPago VARCHAR(30) NOT NULL, 
    MontoPago DECIMAL(10,2) NOT NULL,
    FechaPago DATE NOT NULL,
    IdEstadoPago VARCHAR(30) NOT NULL, 
    Referencial INT,
    FOREIGN KEY (IdPedido) REFERENCES PEDIDO(Id),
    IdEstado  TINYINT FOREIGN KEY  REFERENCES ESTADO (Id)
);


CREATE TABLE PLATO (
    Id INT PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(50) NOT NULL,
    FOREIGN KEY (IdMENU) REFERENCES MENU(Id),
    IdEstado  TINYINT FOREIGN KEY  REFERENCES ESTADO (Id)
);


CREATE TABLE MENU (
    Id INT PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(100) NOT NULL,
    Precio DECIMAL(10,2) NOT NULL,
    IdPlato INT NOT NULL,
    FOREIGN KEY (IdPlato) REFERENCES PLATO(Id),
    IdEstado  TINYINT FOREIGN KEY  REFERENCES ESTADO (Id)
);

GO