<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuenSabor.Restaurante.EntidadesDeNegocios\BuenSabor.Restaurante.EntidadesDeNegocios.csproj" />
    <ProjectReference Include="..\BuenSabor.Restaurante.LogicaDeNegocios\BuenSabor.Restaurante.LogicaDeNegocios.csproj" />
  </ItemGroup>

</Project>
