<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="CargoDAL.cs" />
    <Compile Remove="ClienteDAL.cs" />
    <Compile Remove="ClienteTipoDAL.cs" />
    <Compile Remove="DepartamentoDAL.cs" />
    <Compile Remove="DistritoDAL.cs" />
    <Compile Remove="EmpleadoDAL.cs" />
    <Compile Remove="EmpleadoTurnoDAL.cs" />
    <Compile Remove="EstadoCargoDAL.cs" />
    <Compile Remove="EstadoDAL.cs" />
    <Compile Remove="EstadoPagoDAL.cs" />
    <Compile Remove="EstadoPedidoDAL.cs" />
    <Compile Remove="MenuDAL.cs" />
    <Compile Remove="MesasDAL.cs" />
    <Compile Remove="MetodoPagoDAL.cs" />
    <Compile Remove="MunicipioDAL.cs" />
    <Compile Remove="PagoDAL.cs" />
    <Compile Remove="PedidoDAL.cs" />
    <Compile Remove="ReservacionDAL.cs" />
    <Compile Remove="ReservaClienteDAL.cs" />
    <Compile Remove="TipoClienyteDAL.cs" />
    <Compile Remove="TurnoDAL.cs" />
    <Compile Remove="UbicacionMesaDAL.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuenSabor.Restaurante.EntidadesDeNegocios\BuenSabor.Restaurante.EntidadesDeNegocios.csproj" />
  </ItemGroup>

</Project>
